CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C       Written by: Anshuk Attri
C
C       Contact: contact@anshukattri.in
C       Website: www.anshukattri.in/research
C       GITHUB: github.com/aa-tree/
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


        SUBROUTINE CONVERGENCE_TEST_VECTOR(V_VECTOR, VDIM, VSEED,
     & V_ERRRANGE, O_RESULT)

        REAL*8 V_VECTOR(3,VDIM), O_RESULT(3,VDIM)
        REAL*8 V_ERRRANGE
        INTEGER VSEED, VDIM

C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

        REAL*8 ERROR(3,VDIM),T_ERR(3)
        INTEGER I,J

        DO J=1,VDIM
            DO I=1,3

            END DO
        END DO







        RETURN
        END SUBROUTINE
